Traceback (most recent call last):
  File "/home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/train.py", line 208, in <module>
    main(args)
  File "/home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/train.py", line 52, in main
    train_loader, val_loader, test_loader = get_data_loaders(args.data_dir, args.batch_size, use_data_augmentation=args.use_data_augmentation)
  File "/home/speech/da6401/A2/mod_17a/GIT/da6401_assignment2/partA/data_loader.py", line 33, in get_data_loaders
    full_train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=train_transform)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super().__init__(
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 219, in find_classes
    return find_classes(directory)
  File "/home/speech/.conda/envs/dl_things/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 41, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: 'data/inaturalist_12K/train'
